---
title: "Warderobe visibility"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

"Threddit" is my project attempting to build a proper understanding of the real cost, and eventually carbon footprint, of my use of clothes.

### Real cost per wear
As opposed to the traditional accounting approach of depreciating an asset over its expected lifetime, I track the actual use of each asset (piece of clothing) to determine its real cost per wear and frequency of use. This enables studying the correlation between price and quality (are expensive clothes more durable), as well as real use vs imagined use.

### Cost of utility
Since the use data is exhaustive both in terms of pieces of clothing and time (days), the portfolio level shows the complete and total use by category (kind of clothing). This enables studying the cost of the "utility of clothing" per category and as a whole. This makes the use of clothes comparable to not only other types of physical assets that deteriorate with use, but to "utility" service models (XaaS), both physical and intangible. 

### Data
The data set contains of all pieces of garnment and wear data for each day from 1 Januery 2018 to date. As garnments, such as winter jackets and shoes, may last multiple seasons, it takes 2-3 years of use data for the actual cost to emerge. Daily data input is in Google Sheets. Data processing and plotting in R. Publishing on GitHub Pages.

### Going forward
This project has been quite insightful so far. I'm looking into somehow adding the carbon footprint perspective to also optimise against.
